### ISSUE TITLE
Sobol sample returning same values

### ISSUE THREAD

**Issue by hudsonb22** [SALib/SALib#600] opened 2023-12-15 23:24 UTC
I am trying to run sensitivity analysis on an ODE model using the Sobol sample method. When I run 
`sp.sample_sobol(N, skip_values=X).evaluate(model_wrapper).analyze_sobol()`
I just get 0 or NaN values for all the sensitivities. When I isolate the `sample_sobol()` method, i.e. `b = sp.sample_sobol(N,skip_values=X)`, the sampler just returns many identical arrays regardless of what I use for N or skip_values. Is there any workaround for this?

**Comment by ConnectedSystems** [comment] 2023-12-15 23:26
Thanks for raising the issue.

While I look into this, could you provide an example of the Problem specification?

Thank you

**Comment by ConnectedSystems** [comment] 2023-12-15 23:33
I can't replicate the issue with the usual example we use:

```python
import numpy as np
from SALib import ProblemSpec
from SALib.test_functions import Ishigami

# Create the SALib Problem specification
sp = ProblemSpec(
    {
        "names": ["x1", "x2", "x3"],
        "groups": None,
        "bounds": [[-np.pi, np.pi]] * 3,
        "outputs": ["Y"],
    }
)

sp.sample_sobol(1024)

sp.samples
# Output:
# array([[ 1.82364685,  0.92160128,  1.62839344],
#        [-0.95249319,  0.92160128,  1.62839344],
#        [ 1.82364685,  1.62461207,  1.62839344],
#        ...,
#        [-0.59900446, -0.22952978, -1.78869865],
#        [-0.59900446,  2.87376807, -2.44310292],
#        [-0.59900446,  2.87376807, -1.78869865]])
```

I'll need to see an example of your Problem specification it seems.

**Comment by hudsonb22** [comment] 2023-12-15 23:41
Here is the problem specification:
```
problem = {
    'num_vars': 105,
    'names': arr_str,
    'bounds': np.column_stack((lower_bound_params,upper_bound_params))
}
sp = ProblemSpec(problem)
```
where `arr_str` is an array of names

**Comment by ConnectedSystems** [comment] 2023-12-15 23:58
Hmm, I suspected maybe an issue with `np.column_stack` being misinterpreted but I'm still unable to reproduce the issue.

```python
import numpy as np
from SALib import ProblemSpec
from SALib.test_functions import Ishigami

lb, ub = [-np.pi, -np.pi, -np.pi], [np.pi, np.pi, np.pi]

# Create the SALib Problem specification
sp = ProblemSpec(
    {
        "names": ["x1", "x2", "x3"],
        "groups": None,
        "bounds": np.column_stack((lb, ub)),
        "outputs": ["Y"],
    }
)

sp.sample_sobol(1024, skip_values=16)

sp.samples
# array([[ 0.94726519,  1.84072529,  3.08057069],
#        [-0.44726   ,  1.84072529,  3.08057069],
#        [ 0.94726519, -1.09324237,  3.08057069],
#        ...,
#        [ 2.41776668, -1.07655173,  0.21596603],
#        [ 2.41776668, -1.80299685, -0.31768519],
#        [ 2.41776668, -1.80299685,  0.21596603]])
```

When you say the sample contains many identical arrays, what does this mean precisely? That you see values repeat? Or that entire columns are effectively constant?

Would you be able to provide an example sample?

**Comment by hudsonb22** [comment] 2023-12-16 00:15
When I run just the sample line, I get:
`Samples:
	105 parameters: ['p[0]', 'p[1]', 'p[2]', 'p[3]', 'p[4]', 'p[5]', 'p[6]', 'p[7]', 'p[8]', 'p[9]', 'p[10]', 'p[11]', 'p[12]', 'p[13]', 'p[14]', 'p[15]', 'p[16]', 'p[17]', 'p[18]', 'p[19]', 'p[20]', 'p[21]', 'p[22]', 'p[23]', 'p[24]', 'p[25]', 'p[26]', 'p[27]', 'p[28]', 'p[29]', 'p[30]', 'p[31]', 'p[32]', 'p[33]', 'p[34]', 'p[35]', 'p[36]', 'p[37]', 'p[38]', 'p[39]', 'p[40]', 'p[41]', 'p[42]', 'p[43]', 'p[44]', 'p[45]', 'p[46]', 'p[47]', 'p[48]', 'p[49]', 'p[50]', 'p[51]', 'p[52]', 'p[53]', 'p[54]', 'p[55]', 'p[56]', 'p[57]', 'p[58]', 'p[59]', 'p[60]', 'p[61]', 'p[62]', 'p[63]', 'p[64]', 'p[65]', 'p[66]', 'p[67]', 'p[68]', 'p[69]', 'p[70]', 'p[71]', 'p[72]', 'p[73]', 'p[74]', 'p[75]', 'p[76]', 'p[77]', 'p[78]', 'p[79]', 'p[80]', 'p[81]', 'p[82]', 'p[83]', 'p[84]', 'p[85]', 'p[86]', 'p[87]', 'p[88]', 'p[89]', 'p[90]', 'p[91]', 'p[92]', 'p[93]', 'p[94]', 'p[95]', 'p[96]', 'p[97]', 'p[98]', 'p[99]', 'p[100]', 'p[101]', 'p[102]', 'p[103]', 'p[104]']
	13568 evaluations `

And the input array p to my model:
```
p : [ 3.40279036e-03  6.65422723e+00  1.10990556e+00  1.34706784e-01
  3.53723913e+02  1.24775555e+03  3.40560121e-04  1.48856785e-04
  6.55922478e-05  4.89766568e-06  8.26293527e-01  2.56697850e-02
  9.04710932e-03  3.15202582e+00  8.90937583e-04  9.33600740e+01
  7.29335737e-04  9.70571361e-02  1.73292469e-04  6.00770604e+00
  9.34681536e-02  6.72239527e+01  2.38501167e+03  5.04115754e-03
  2.45999578e-03  7.28573824e-04  6.43488610e-04  1.02843829e+00
  2.18201846e-01  6.40212838e+02  1.20749026e+02 -9.97449018e-05
  3.02141205e+00  4.48644820e-01  1.37153969e-01  2.91915996e+01
  8.20415045e-02  3.04452619e-01  5.23192445e-03  2.98236003e-02
  4.62067280e-03  3.00489018e+00  1.84638506e+00  1.04522933e-01
  1.70965027e+00  1.74166291e-01  3.48332304e+00  5.16198690e+00
  3.63659200e+00  3.79670698e+00  7.11663535e+00  8.32021397e+00
  8.63496967e+00  1.60554115e+01 -7.34719446e-05  5.06585471e-05
  5.43667607e-01  6.87645279e-01  1.26009787e+00  6.71023289e-01
  5.39858062e+00  1.10898917e-01  2.42637400e-01  1.19995053e-01
  2.66596494e+01  1.68264420e+01  5.19733025e-01  5.71080174e-05
  1.08311090e+00  1.45767347e+00  8.72921127e-01  9.77823585e-01
  1.62857343e-06  1.36952240e+00  1.28460627e+00  1.05561835e+00
  8.08719565e-01  1.97345768e+00  1.55664786e+00  1.35185322e+00
 -6.63774349e-06  6.88877195e-05  3.34652803e-04  8.87953176e-03
  5.24379881e-01  4.55056691e+06  1.05788433e+05  1.81281537e+02
  2.78624662e-01  5.12557724e-03  1.20766245e-01  1.42812655e+03
  8.27734083e-03  2.94749544e+01  1.38186866e+06  2.89465181e+06
  5.91655293e+04  1.05167900e+03  5.53260089e-04  1.72085538e+01
  6.76318820e-01  1.03820940e+00  1.01099466e+00  7.00199815e-01
  1.11257497e+00]
```
The array of samples passed to the function is always the same, regardless of sample number

**Comment by ConnectedSystems** [comment] 2023-12-16 00:20
Where does `p` come from in this case?

The generated samples are stored in `sp.samples`, which are the inputs to your model

**Comment by ConnectedSystems** [comment] 2023-12-16 00:21
Ah, I think I know what's happening.

Could you show me your model wrapper? I suspect it's only taking the first row of the sample matrix or similar.

**Comment by hudsonb22** [comment] 2023-12-16 00:47
Here's the wrapper:
`def wrapper_thyrosimIM(X, func=thyrosimIM):
    
    print(f"input arr: {X}")
    print(X.shape)

    time_points = np.linspace(0, 100, 1000)

    result = np.zeros((X.shape[0], 24))

    for element in range(X.shape[0]):
        wrapper_params = X[0]
        wrapper_params = wrapper_params.flatten()
        #print(f"wrap params: {wrapper_params}")
        #print(f"shape: {wrapper_params.shape}")

        a = func(ics, time_points, wrapper_params)

        result[element] = np.array(func(ics, time_points, wrapper_params))


    print(f"input arr: {X}")
    print(X.shape)

    #print(result)
    return result`

You're saying the issue is in not iterating through X?

**Comment by ConnectedSystems** [comment] 2023-12-16 01:00
This line here:

`wrapper_params = X[0]`

Just takes the first row (so the first parameter set).

You want something more like:

```python
for element, params in enumerate(X):
        wrapper_params = params.flatten()  # not sure if this is needed, I think you can use `params` directly
        # ... etc ...
```

Just to show this is working as expected with the example given above

```python
for i, params in enumerate(sp.samples):
    print(i, params)
    break

# Display just to show it's the first row as above
print(sp.samples[0])
```

See the example here for more info: https://salib.readthedocs.io/en/latest/user_guide/wrappers.html

Hope this helps!

**Comment by ConnectedSystems** [comment] 2024-01-05 11:24
Closing under the assumption that this issue is now resolved. 

Feel free to reopen and ask more questions if needed!

**Closed by ConnectedSystems** 2024-01-05 11:24 UTC
