### ISSUE TITLE
Odd Sobol first order indices

### ISSUE THREAD

**Issue by Anto-F** [SALib/SALib#109] opened 2016-10-25 15:23 UTC
Hello,
I compare some tools and methods to calculate Sobol indices and I got some strange values for first order indices with SALib.

With Polynomial Chaos (openturns) and EASI algorithm, I have the following results for S1's:

```
    Polynomial Chaos    EASI
x1  0.48                0.48
x2  0.25                0.25
x3  0.10                0.11
x4  0.04                0.05
x5  0.04                0.04
x6  0.03                0.03
x7  0.02                0.02
x8  0.02                0.02
x9  0.02                0.02
x10 0.01                0.01
```

As you can see, they converge to the same values.
And 500 simulations with a Quasi Monte-Carlo sample is enough to reach these values (I tried up to 2000 simulations and they remain the same).
Also, the ST's I got with Polynomial Chaos are similar to the S1's (EASI doesn't include this calculation).

With Salib I use saltelli.sample to generate 5000 samples and I have the following results:

```
    S1      S1_conf  ST  ST_conf
x1  0.92    4.99    0.53    0.06
x2  0.29    2.37    0.16    0.02
x3  0.22    1.70    0.11    0.01
x4  0.25    1.24    0.05    0.01
x5  0.04    1.14    0.04    0.01
x6  0.03    0.98    0.03    0.00
x7  -0.09   1.01    0.02    0.00
x8  0.05    0.98    0.02    0.00
x9  0.06    0.83    0.02    0.00
x10 0.02    0.82    0.01    0.00
```

Except for the second parameter, the ST's are really close to what I got with other methods.
However, the S1's don't look good and the confidence intervals are terrible.
I don't understand why SALib is able to calculate ST's but not S1's in my case, specially if they have similar values.
I could increase the sample size but 5000 took 80 hours...
Any thoughts on this issue ?

**Comment by jdherman** [comment] 2016-10-25 15:48
Thanks @Anto-F . This sounds similar to #102 . At first I thought this was a function-specific problem but now I'm wondering if there is a bug in the S1 calculation.

I'll look into it. Could you say more about the function?

**Comment by Anto-F** [comment] 2016-10-25 15:58
I read the #102 before posting and yes, it sounds similar.
My function is a whole software, [EnergyPlus](http://apps1.eere.energy.gov/buildings/energyplus/), for building energy simulation.

**Comment by jdherman** [comment] 2016-10-25 16:17
Ok. A couple of questions:
- Is the model deterministic? 
- Do you expect a high degree of interactions?
- Can you confirm that the Ishigami function example in the readme works?

@rJonatan noticed the same issue for the function:
```
f(x) = x[0] + 2*x[1]*x[2] + 4*x[3]*x[4]*x[5] + 8*x[6]*x[7]*x[8]*x[9]
```
Sampled over `[0.9, 1.1]^10` with `N=10000`, which similarly had good results for ST but not for S1. 
```
Parameter S1 S1_conf ST ST_conf
x1 0.006618 0.023523 0.003145 0.000090
x2 0.008847 0.041397 0.012828 0.000424
x3 0.011921 0.046918 0.012793 0.000350
x4 0.046414 0.098711 0.051961 0.001446
x5 0.065158 0.089824 0.050899 0.001288
x6 0.030582 0.082876 0.051003 0.001610
x7 0.180874 0.177608 0.206429 0.006840
x8 0.247405 0.192230 0.207822 0.005955
x9 0.177546 0.174891 0.207631 0.005707
x10 0.235470 0.181401 0.205767 0.006151
```

I'm wondering if this is related to functions with a high degree of interaction in the parameters. I haven't noticed it in any of the test cases before.

**Comment by Anto-F** [comment] 2016-10-25 16:42
The Morris analysis does not show high interactions (std very much less than absolute mean for these parameters).
However the model is complex and can be seen as a black box... 
No problem with the Ishigami fonction.

**Comment by Anto-F** [comment] 2016-10-26 13:51
I tried this function and got similar results for ST's but not for S1's.
Also, EASI algorithm gives relatively close results.
```
problem = {
  'num_vars': 10, 
  'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10'],
  'bounds': [[0.9, 1.1]]*10
}

X = saltelli.sample(problem, N=1000, calc_second_order=False)
Y = X[:,0] + 2*X[:,1]*X[:,2] + 4*X[:,3]*X[:,4]*X[:,5] + 8*X[:,6]*X[:,7]*X[:,8]*X[:,9]
Si = sobol.analyze(problem, Y, print_to_console=True, calc_second_order=False)

	SAL_S1	SAL_ST	EASI_S1
x1	0.0024	0.0032	0.0037
x2	0.0107	0.0128	0.0113
x3	0.0126	0.0128	0.0129
x4	0.0527	0.0515	0.0522
x5	0.0461	0.0498	0.0510
x6	0.0599	0.0513	0.0498
x7	0.2065	0.2058	0.2036
x8	0.1712	0.1985	0.2043
x9	0.2225	0.2095	0.2056
x10	0.2008	0.2030	0.1993
```
Same comparison with Ishigami function, which works fine:
```
	SAL_S1	SAL_ST	EASI_S1
x1	0.306	0.560	0.307
x2	0.448	0.439	0.445
x3	-0.001	0.243	0.000
```
It may not be a bug but rather a limitation of the method.

**Comment by jdherman** [comment] 2016-10-26 16:25
Thanks for running this. We do have the same results, the only difference is whether the second-order indices are included or not. The sampling is quasi-random so the results should be the same every time.

Here is the full output with confidence intervals:
```
Parameter S1 S1_conf ST ST_conf
x1 0.002447 0.077269 0.003158 0.000298
x2 0.010691 0.136656 0.012801 0.001209
x3 0.012604 0.131934 0.012758 0.001225
x4 0.052731 0.274459 0.051532 0.005217
x5 0.046075 0.275380 0.049776 0.005183
x6 0.059868 0.282382 0.051296 0.004491
x7 0.206501 0.623697 0.205779 0.019611
x8 0.171222 0.593937 0.198511 0.017142
x9 0.222532 0.582412 0.209502 0.017824
x10 0.200843 0.532377 0.203015 0.020176
```

I noticed by changing the bounds to `[-10,10]` and increasing sample size to N=10000, the results seem more like what you'd expect:
```
Parameter S1 S1_conf ST ST_conf
x1 0.000001 0.000018 0.000000 0.000000
x2 -0.000056 0.000223 0.000056 0.000003
x3 0.000026 0.000227 0.000056 0.000003
x4 0.000515 0.002309 0.007659 0.000518
x5 -0.000114 0.002321 0.007427 0.000477
x6 0.000602 0.002229 0.007510 0.000533
x7 -0.006703 0.033183 0.990898 0.059457
x8 -0.004478 0.033923 0.923021 0.055368
x9 -0.001745 0.039921 0.993586 0.059560
x10 -0.006752 0.035732 1.014584 0.061766
```
All of the sensitivity now is in the ST's of the last 4 parameters, which makes sense.

I'm interested to see if we can narrow down when this happens. If anyone has quick access to other Sobol implementations in Sobol/Matlab, does this made-up function give similar results?

I looked again at `sobol.analyze` and I'm fairly confident that it's doing what it's supposed to. It works on test functions, but I know these real-life models go far beyond the complexity of test functions. 

My current guess is that small parameter ranges lead to small total variance. All of the indices are normalized by total variance, so if the sampling ranges aren't wide enough, maybe something unexpected happens in the method (?) Although I would expect it to also happen to the ST's. 

Here is the code for first/total order given outputs from matrices A, B, and AB (from cross-sampling).

```python
def first_order(A, AB, B):
    # First order estimator following Saltelli et al. 2010 CPC, normalized by
    # sample variance
    return np.mean(B * (AB - A), axis=0) / np.var(np.r_[A, B], axis=0)


def total_order(A, AB, B):
    # Total order estimator following Saltelli et al. 2010 CPC, normalized by
    # sample variance
    return 0.5 * np.mean((A - AB) ** 2, axis=0) / np.var(np.r_[A, B], axis=0)
```

**Comment by Anto-F** [comment] 2016-10-27 09:24
Very interesting.
If you only increase the sample size (I tried up to N=100000), you get similar results for S1's and ST's:
```
Parameter   S1  S1_conf ST  ST_conf EASI S1
x1  0.003222    0.006827    0.00318     0.000031    0.003175
x2  0.012762    0.015698    0.012764    0.000123    0.012697
x3  0.012683    0.013658    0.012764    0.000115    0.012688
x4  0.050886    0.029006    0.051228    0.000479    0.050772
x5  0.050863    0.029007    0.051214    0.00048     0.050765
x6  0.050853    0.028898    0.051227    0.000422    0.050758
x7  0.20334     0.063935    0.205581    0.001945    0.203076
x8  0.203533    0.063192    0.205456    0.001706    0.203051
x9  0.203654    0.06626     0.205619    0.001993    0.203032
x10 0.203158    0.058609    0.205584    0.002051    0.202982
```
And once again, same results with EASI algorithm.
So, do you think we can trust this results ? 
With "small" sample size, SALib can't evaluate S1's for some functions, while they should be very close to the ST's (as for rJonatan and me).
For my model I can't check if the sample size solves the problem, as it will take more than a week of calculation, just for a N of about 1000.
If these results are correct, EASI or PC seem to be a good alternative for S1's as they require much less evaluations.

**Comment by Anto-F** [comment] 2016-10-27 14:03
More validations with openturns this time (SobolIndicesAlgorithm and SaltelliSensitivityAlgorithm).
With rJonatan's function I got the following results:

```
Sobo_ S1	Sobol_ST	Saltelli_S1	Saltell_ST
0.00338	0.00318	0.00313	0.00322
0.01292	0.01278	0.01266	0.01319
0.01303	0.01275	0.01277	0.01267
0.05103	0.05106	0.05075	0.05102
0.05078	0.05127	0.05048	0.05172
0.05147	0.05127	0.05116	0.05198
0.20488	0.20550	0.20461	0.20513
0.20317	0.20495	0.20271	0.20534
0.20339	0.20542	0.20313	0.20501
0.20250	0.20499	0.20215	0.20493
```
Quite close to SALib with a suitable sample size.

**Comment by jdherman** [comment] 2016-10-27 17:37
Thanks @Anto-F. So it sounds like it's a sample size issue. There is something strange about these particular functions/models that makes it hard to converge the S1 values. Maybe the high degree of interactions? I'm not sure.

Using the `delta` method from Plischke et al. (which also calculates S1 values from given data), it gets about the right values again with only N=1000:
```python
X = latin.sample(problem, N=1000)
Y = X[:,0] + 2*X[:,1]*X[:,2] + 4*X[:,3]*X[:,4]*X[:,5] + 8*X[:,6]*X[:,7]*X[:,8]*X[:,9]
Si = delta.analyze(problem, X, Y, print_to_console=True)
```
```
Parameter delta delta_conf S1 S1_conf
x1 0.033451 0.016388 0.011163 0.014221
x2 0.053459 0.018343 0.029479 0.024645
x3 0.032627 0.008746 0.005375 0.012678
x4 0.072695 0.012604 0.065710 0.023116
x5 0.053538 0.016587 0.034520 0.028425
x6 0.046217 0.015398 0.034059 0.023203
x7 0.146098 0.018534 0.210237 0.052198
x8 0.170412 0.021655 0.222191 0.031501
x9 0.166859 0.023235 0.211119 0.036852
x10 0.185545 0.028857 0.223418 0.043526
```

We can leave this issue open in case anyone has more insight, but it may just be a limitation of the method.

**Comment by Anto-F** [comment] 2016-11-03 12:29
Thanks for the `delta.analyze`, I didn't know there was another method to calculate the S1 values from given data.
Usually I use EASI (also from Plischke) for quick calculation and `sobol_first()` method is surprisingly simpler !

A quick note on the problem definition. It took me some time to find that a _dists_ argument can be added with `saltelli.sample`.
I had to reach the `nonuniform_scale_samples()` method to find the possibilities. Maybe it should be included in the [Concise API Reference](http://salib.readthedocs.io/en/latest/api.html).

In my first post, the comparison between PC and SALib was done with different distributions (mainly truncated normal for PC and uniform for SALib) and this has a non negligible impact.
Indeed, this has nothing to do with the sample size issue for S1 but this explains the difference for ST.
I run new simulations with only uniform distributions and I got the following results:
```
PC_S1  	PC_ST	SALib_ST
0.531	0.532	0.525
0.160	0.161	0.158
0.114	0.114	0.112
0.052	0.052	0.052
0.041	0.041	0.041
0.028	0.029	0.029
0.022	0.022	0.022
0.018	0.019	0.019
0.017	0.018	0.017
0.013	0.014	0.014
```
Now I have to add the truncated distribution into SALib to compute my real case.

**Comment by jdherman** [comment] 2016-11-05 00:44
Ok, that's good news. Those ST's seem to match.

You can transform a uniform sample into any other distribution using the inverse CDF of the target distribution. This is how the built-in distributions work, but we didn't think it would be possible to have a comprehensive set of distributions included, when it's relatively easy to transform the samples after getting the uniform ones from SALib.

Inside `nonuniform_scale_samples()` here's an example:
```python
conv_params[:,i] = sp.stats.norm.ppf(params[:,i], loc=b1, scale=b2)
```
it's just the inverse normal CDF with a specified mean and standard deviation.

**Comment by Anto-F** [comment] 2016-11-05 09:54
Already done, simulations are running.
Problem["bounds"] is used to set the min and max values so I had to create another key for the mean and std of the distribution.
There is also a little change to do on min and max values according to scipy truncnorm documentation.
I validated my distributions with openturns so I'm confident about it.

**Comment by Anto-F** [comment] 2016-11-08 09:32
So I have added truncated normal distribution in SALib and this is what I get for the ST's (comparison with openturns PC):
```
PC_ST	Salib_ST	SALIB ST_conf
0.479	0.490	0.060
0.246	0.251	0.030
0.102	0.099	0.013
0.046	0.047	0.007
0.037	0.038	0.005
0.028	0.030	0.005
0.020	0.020	0.003
0.017	0.017	0.003
0.016	0.016	0.002
0.011	0.011	0.002
```
No problem here.
Still an issue with SALib S1's but not sure there is a solution for this one.

**Comment by jdherman** [comment] 2016-12-20 23:05
@Anto-F and @rJonatan --

Looking at #114 for the same function above, it seems to fix the problem:

```python
from SALib.sample import saltelli
from SALib.analyze import sobol

problem = {
  'num_vars': 10, 
  'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10'],
  'bounds': [[0.9,1.1]]*10
}

X = saltelli.sample(problem, N=1000, calc_second_order=False)

Y = X[:,0] + 2*X[:,1]*X[:,2] + 4*X[:,3]*X[:,4]*X[:,5] + 8*X[:,6]*X[:,7]*X[:,8]*X[:,9]

Y = (Y - Y.mean())/Y.std()

Si = sobol.analyze(problem, Y, calc_second_order=False, print_to_console=True)
```

This transforms the distribution of model output to a standard normal (assuming the output is approximately normal in the first place). This gives the following results (N=1000):

```
Parameter S1 S1_conf ST ST_conf
x1 0.002850 0.004360 0.003158 0.000243
x2 0.013963 0.010275 0.012801 0.001213
x3 0.012140 0.009235 0.012758 0.001087
x4 0.053325 0.021080 0.051532 0.004621
x5 0.051033 0.021097 0.049776 0.004415
x6 0.051152 0.018187 0.051296 0.004464
x7 0.201484 0.036013 0.205779 0.017242
x8 0.200369 0.035185 0.198511 0.018646
x9 0.204063 0.042718 0.209502 0.016890
x10 0.202586 0.032653 0.203015 0.017365
```

This looks much better. When you have time, could you both try this and confirm? If it works, I'll put the transformation inside the sobol.analyze() function so that it doesn't change the actual values.

**Comment by sofianehaddad** [comment] 2016-12-21 11:20
Hi
Saltelli method is indeed very sensitive to non centered data. 

You can take for example the usual Ishigami function for which Sobol indices are known analytically.
If we use a decentered Ishigami function (f = Ishigami + C, C a constant equals to 1000 for example), then results may totally differ even if we except same sobol features as for classicial Ishigami!

See for example https://gist.github.com/sofianehaddad/f3bb2ac1b9c20fbf739fad7a1994dd1f

I had the following results with that script:

>  Usual Ishigami
[ 0.30644324  0.44776661 -0.00104936]
[ 0.56013728  0.4387225   0.24284474]
Decentered Ishigami
[-0.1306285   0.44776661  0.91322048]
[ 0.56013728  0.4387225   0.24284474]

The issue is indeed to add the discussed transformation or to use other methods that are known to be less sensitive (Jansen for example http://doc.openturns.org/papers/jansen1999.pdf)

**Comment by jdherman** [comment] 2016-12-21 18:39
@sofianehaddad thanks! This is a useful example. So to center the output, is it considered best practice to: (1) subtract the mean, (2) subtract the median, or (3) do `(Y - mean) / std` as above?

For anyone else following this discussion, I don't think it means that any prior first-order results are wrong -- it still seems to converge with a large enough sample size. but this fix should make it more efficient.

**Comment by sofianehaddad** [comment] 2016-12-22 10:32
@jdherman I'll choose (3)
Otherwise you're right! In case of non centered outputs, Saltelli's convergence requires large sample size and the fix will perform it

**Comment by Anto-F** [comment] 2017-01-04 13:06
@jdherman Thanks for the fix.
It's better but with N=1000 the confidence level is still not satisfying (20% for the largest S1 in your example).
It still requires a very large N which I cannot use with my model (more than two weeks of calculation). 
However, the values seem good to me (same as other methods).
It's just a sample size issue due to the model "complexity". As @sofianehaddad said, this may be expected with this method.

**Comment by jdherman** [comment] 2017-01-04 16:19
Ok I understand. Thanks again for raising the issue and testing it out. I haven't made this change in the master branch yet, it's on my to-do list.

In the case of a complex model, you could get away with fewer samples using maybe the DGSM or Morris methods. Another option, if you want to get Sobol indices, would be to build a metamodel (SALib does not have this built in).

**Comment by Anto-F** [comment] 2017-01-04 16:35
I already built a metamodel (PCE) with the python library OpenTurns, it's also an interesting approach and worked well for my model.
Else, the `delta.analyze` in Salib seems to provide a good estimation of S1's with much less model evaluations than Saltelli method (but it does not calculate the ST's).

**Comment by jdherman** [comment] 2017-01-07 23:41
@Anto-F @sofianehaddad @rJonatan

This is fixed in the new version. Thanks for your help! I'm going to push to PyPI in a minute, then you should be able to update the library.

**Closed** 2017-01-07 23:42 UTC
Labels: question
