### ISSUE TITLE
Singular matrix issue when computing delta indeces

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#241] opened 2019-05-09 21:03 UTC
Hi there,

I noted that there are two closed incidents on this topic (#152 and #1510), as well a recent one (#240). But I believe that the issue I'm having is different to those that were reported.

I am using Python 3.6.5 on a windows machine and SALib 1.3.3

I conducted a series of tests using four input parameters to derive a single output. There are four scenarios, so I want to evaluate Delta indices in each scenario for different bootstrap levels by using the following code (note that I consider "resamples" option in Delta index as the number of samples to be taken in bootstrap procedure):

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
problem= {
        'num_vars': 5,
        'names': ['input_1', 'input_2', 'input_3', 'input_4', 'input_5'],
        'bounds': [[min_input_1, max_input_1],
                   [min_input_2, max_input_2],
                   [min_input_3, max_input_3],
                   [min_input_4, max_input_4],
                   [min_input_5, max_input_5]],
        }

Si= []

filename= 'delta_moment_3d_orig_n_noise_class_'
figure_name= 'delta_moment_3d_orig_n_noise_class_'

label= 'Free noise wedge model'

attribute_names= ['input_1', 'input_2', 'input_3', 'input_4', 'input_5']

bootstrap= 0    

print("Perform Delta-Moment Independent Test\n")

for count in range(0,len(classification_names)): # Test different scenarios
    filename= filename + np.str(count + 1) + '.csv'
    figure_name= figure_name + np.str(count + 1)
    
    output_file= open(path + filename, 'w')
    
    for iters in range(0,4): # Test different bootstrap levels
        bootstrap += 200
    
        print("using a bootstrap sampling of {} at iteration {} and count {}\n".format(bootstrap, iters, count))

        Si= delta.analyze(problem, attribute_data, classification_data[:,count], num_resamples= bootstrap, print_to_console= True)

        if (bootstrap == 200):
            field_names= []
        
            for key in Si:
                field_names.append(str(key))
            
            output_file.write("%s %s %s %s %s %s %s %s %s %s %s\n" %("attribute name", ',', field_names[0], ',',
                                                                     field_names[1], ',', field_names[2], ',', field_names[3], ',',
                                                                     "bootstrap level"))

        delta_r= Si.get('delta')
        delta_conf_r= Si.get('delta_conf')
        sobol_r= Si.get('S1')
        sobol_conf_r= Si.get('S1_conf')

        for i in range(0, len(delta_r)):
            output_file.write("%s %s %2.5f %s %2.5f %s %2.5f %s %2.5f %s %s\n" %(attribute_names[i], ',', delta_r[i], 
                                                                             ',', delta_conf_r[i], ',', sobol_r[i], ',',
                                                                             sobol_conf_r[i], ',', str(bootstrap)))
        
        print("\n")

    output_file.close()
    
    SA= pd.read_csv(path + filename, delimiter= ',')
    plot_histograms(SA, label, figure_name)
    
    filename= 'delta_moment_3d_orig_n_noise_class_'
    figure_name= 'delta_moment_3d_orig_n_noise_class_'
    
    Si= []

    bootstrap= 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

So, I checked for bootstrap levels at 200, 400, 600, and 800. All input data are 1D arrays of length 20099 samples. When the script reaches the second scenario for a bootstrap of 600, the following error message occurs:

using a bootstrap sampling of 600 at iteration 2 and count 2

Parameter delta delta_conf S1 S1_conf
Input_1 0.313084 0.004628 0.081716 0.010388
Input_2 0.436194 0.008330 0.371258 0.012746

Traceback (most recent call last):
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 75, in analyze
    Y, Ygrid, X[:, i], m, num_resamples, conf_level)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 115, in bias_reduced_delta
    d[i] = calc_delta(Y[r], Ygrid, X[r], m)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 101, in calc_delta
    fyc = gaussian_kde(Y[ix], bw_method='silverman')(Ygrid)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\linalg\basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Run_sa_3d_results.py", line 202, in <module>
    Si= delta.analyze(problem, attribute_data, classification_data[:,count], num_resamples= bootstrap, print_to_console= True)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 85, in analyze
    raise np.linalg.LinAlgError(msg)
numpy.linalg.linalg.LinAlgError: Singular matrix detected
             Sample size of 20099 may be too small

For some reason, Delta function considers that there not enough samples. However, the script was able to perform 10 computations.

In the attached file, you will find the input data:
A) Model input: input_1, input_2, input_3, input_4, input_5
B) Model output: output_1, output_2, output_3, output_4
C) Python script

Many thanks for your help!

Ivan

[Delta_indices.zip](https://github.com/SALib/SALib/files/3163999/Delta_indices.zip)

**Comment by ConnectedSystems** [comment] 2019-05-12 01:06
Hi Ivan,

I can't seem to reproduce your issue.
Could you check what version of NumPy you have installed?

Your script works for me without issue. I have numpy v1.16.3 in my dev environment.

I note that there was a mistyped filename in your script:
`input__4.txt` had an extra underscore; should be `input_4.txt` instead.

The call to `plt.title` also specified an `s` option which doesn't exist

```python
plt.title(s= 'Delta and Sobol Indices bootstrap: ' + label + ' ' + level, fontsize= 10)

# changed the above to:
plt.title('Delta and Sobol Indices bootstrap: ' + label + ' ' + level, fontsize= 10)
```

Those were the only changes I made.

**Comment by ivan-marroquin** [comment] 2019-05-13 20:16
Hi @ConnectedSystems 

I tested with numpy version 1.16.3 and still got the same problem. 

I was experiencing a similar error problem with another Python package, which is reported in here:
https://github.com/garydoranjr/rdc/issues/1

The developer who helped me found out that there is a potential issue on how the linear algebra library matrix inversion is implemented in Windows. The solution was to use a pseudo-inverse to avoid numerical issues.

When you ran your tests, did you use a windows machine?

Kind regards,
Ivan

**Comment by ConnectedSystems** [comment] 2019-05-13 22:31
Yes, I did indeed run it on Windows.

I can't have a good look at this at the moment as I'm travelling at the moment (I'm writing this at the airport!) but I promise to have a closer look over the next few days.

**Comment by ConnectedSystems** [comment] 2019-05-18 01:00
Hi @ivan-marroquin 

Sorry for the delay in getting back to you - internet access has been limited here.

At this time I still think it's a package version issue. I have set up a Python environment under Ubuntu on Windows (through the subsystem for linux) and still cannot reproduce the issue.

Could you send me the file output when you run and I can look into the differences.

`pip freeze > svm-issue-pkgs.txt`

I've attached the modified script and files I used which you should be able to run directly. Just extract everything into the same directory and it should work. Aside from the earlier changes I've already mentioned, I modified it so it runs `bootstrap sampling of 600 at iteration 2 and count 2` directly as this was where you mentioned the issue occurs.

Also included is the conda environment specification (`svm.yml`) which details all packages and their versions that were installed in my environment. The ones that are commented out are specific to Windows platforms.

If you don't use conda you can modify the file into a pip requirements file and setup a pipenv or similar.

[salib-svm-issue.zip](https://github.com/SALib/SALib/files/3193479/salib-svm-issue.zip)

You can set it up the environment with: 

`conda env create --file svm.yml`

This will create an environment called `salib-svm`. If you'd like a different name, use:

`conda env create --file svm.yml --name YOUR_ENV_NAME`


Let me know how you go.

**Comment by ivan-marroquin** [comment] 2019-05-19 14:03
Hi @ConnectedSystems 

Many thanks for your precious help. I will give a try tomorrow when I am back to the office. I will let you know how it goes.

Ivan

**Comment by ivan-marroquin** [comment] 2019-05-20 19:29
Hi @ConnectedSystems 

As per your request. I sent you the listing of current Python packages. It will take me more time to set up a new environment with the same dependencies as yours - I noted that you have BLAS and MLK, and I wonder how simple is their installation in Windows but I will give a try.

In the meantime, I would like to share these results with you - when I used your edited Python script:

A) Using the file as it is, I get this result:
using a bootstrap sampling of 600 at iteration 2 and count 2

Parameter delta delta_conf S1 S1_conf
input_1 0.313067 0.004609 0.081716 0.010157
input_2 0.436043 0.008002 0.371258 0.012805
input_3 0.429899 0.011110 0.401443 0.014680
input_4 0.363540 0.004496 0.318246 0.015065
input_5 0.427711 0.006657 0.447122 0.012556

The computation ended without problems. Thus, it is difficult to duplicate my issue.

B) Comment out lines 169 and 170:
# if count != 2:
#      continue

This time the script will go through each scenario, and it will compute delta indices only for bootstrap 600. This time, I get the following:

using a bootstrap sampling of 600 at iteration 2 and count 0

Parameter delta delta_conf S1 S1_conf
input_1 0.258528 0.005071 0.025523 0.004927
input_2 0.482448 0.006964 0.591627 0.011788
input_3 0.369528 0.011771 0.318396 0.015449
input_4 0.324718 0.004342 0.164467 0.011379
input_5 0.478547 0.006570 0.631322 0.010683


using a bootstrap sampling of 600 at iteration 2 and count 1

Parameter delta delta_conf S1 S1_conf
input_1 0.263020 0.005696 0.179338 0.009909
input_2 0.310627 0.005349 0.255525 0.009265
input_3 0.408564 0.008584 0.467803 0.017562
input_4 0.228233 0.004438 0.144402 0.009353
input_5 0.308695 0.005524 0.269352 0.011093


using a bootstrap sampling of 600 at iteration 2 and count 2

Parameter delta delta_conf S1 S1_conf
input_1 0.313060 0.004716 0.081716 0.009358
input_2 0.435984 0.007655 0.371258 0.012625
Traceback (most recent call last):
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 75, in analyze
    Y, Ygrid, X[:, i], m, num_resamples, conf_level)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 115, in bias_reduced_delta
    d[i] = calc_delta(Y[r], Ygrid, X[r], m)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 101, in calc_delta
    fyc = gaussian_kde(Y[ix], bw_method='silverman')(Ygrid)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance) # IDM replaced inv by pinv
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\linalg\basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Delta_indices.py", line 189, in <module>
    Si= delta.analyze(problem, attribute_data, classification_data[:,count], num_resamples= bootstrap, print_to_console= True)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 85, in analyze
    raise np.linalg.LinAlgError(msg)
numpy.linalg.linalg.LinAlgError: Singular matrix detected
             Sample size of 20099 may be too small

I am able to duplicate the issue only when I run consecutive computations. Also, if you compare the derived indices for the problematic scenario:
A) when it worked
input_1 0.313067 0.004609 0.081716 0.010157
input_2 0.436043 0.008002 0.371258 0.012805
input_3 0.429899 0.011110 0.401443 0.014680
input_4 0.363540 0.004496 0.318246 0.015065
input_5 0.427711 0.006657 0.447122 0.012556

B) when it failed
input_1 0.313060 0.004716 0.081716 0.009358
input_2 0.435984 0.007655 0.371258 0.012625

They are different. Is this a normal behavior? If so, is there a way to get reproducible results?

Many thanks for your help,

Ivan

[svm-issue-pkgs.zip](https://github.com/SALib/SALib/files/3199486/svm-issue-pkgs.zip)

**Comment by ConnectedSystems** [comment] 2019-05-21 09:58
Hi @ivan-marroquin 

Thanks for your feedback - it was very useful.
I think you're running into the same issue as in #240 as the package versions look comparable.

For deterministic runs, you can set the `seed` parameter in your call to `delta.analyze()`

```
delta.analyze(problem, attribute_data, classification_data[:,count], 
                      num_resamples=bootstrap, print_to_console=True, seed=101)
```

Running the full set as you said, I do indeed run into the issue. With the seed value set to 101 it ran without issue.

Could you please try your script with the following branch of SALib?

```
pip uninstall SALib
pip install git+https://github.com/ConnectedSystems/SALib@delta-analyze-warn
```

**Comment by ivan-marroquin** [comment] 2019-05-21 21:20
Hi @ConnectedSystems 

I tested my old Salib installation by setting a seed, and it worked fine. Then, I deleted Salib and installed your branch - as per your instructions. To confirm, the command pip list shows the entry "SALib (1.1.3.post0.dev129+g0c836d9)"

I tested again but with a different seed. It worked fine as well. 

Thereafter, I decided to used other simulation results. Unfortunately, I bumped into the same issue - as before, it is important to go through the iterations to reveal the issue:

Perform Delta-Moment Independent Test

using a bootstrap sampling of 200 at iteration 0 and count 0

Parameter delta delta_conf S1 S1_conf
Envelope 0.292743 0.005694 0.231516 0.010046
Instantaneous Frequency 0.299244 0.005624 0.250215 0.011661
Instantaneous Phase 0.601531 0.010217 0.830063 0.006619
Relative Acoustic Impedance 0.260646 0.004705 0.243956 0.010688
Thin Bed 0.349083 0.004204 0.349506 0.009502


using a bootstrap sampling of 400 at iteration 1 and count 0

Parameter delta delta_conf S1 S1_conf
Envelope 0.292663 0.006084 0.231516 0.010560
Instantaneous Frequency 0.299004 0.005603 0.250215 0.012129
Instantaneous Phase 0.601433 0.009442 0.830063 0.006724
Relative Acoustic Impedance 0.260892 0.004842 0.243956 0.010345
Thin Bed 0.349229 0.004439 0.349506 0.009099


using a bootstrap sampling of 600 at iteration 2 and count 0

Parameter delta delta_conf S1 S1_conf
Envelope 0.292590 0.006390 0.231516 0.010224
Instantaneous Frequency 0.298742 0.005705 0.250215 0.012404
Instantaneous Phase 0.601007 0.009512 0.830063 0.006683
Relative Acoustic Impedance 0.260758 0.005144 0.243956 0.010063
Thin Bed 0.349168 0.004464 0.349506 0.008643


using a bootstrap sampling of 800 at iteration 3 and count 0

Parameter delta delta_conf S1 S1_conf
Envelope 0.292668 0.005860 0.231516 0.010382
Instantaneous Frequency 0.298826 0.005689 0.250215 0.011332
Instantaneous Phase 0.601516 0.009076 0.830063 0.006829
Relative Acoustic Impedance 0.260736 0.005192 0.243956 0.010509
Thin Bed 0.349359 0.004422 0.349506 0.009161


using a bootstrap sampling of 200 at iteration 0 and count 1

Parameter delta delta_conf S1 S1_conf
Envelope 0.313826 0.006198 0.112802 0.008459
Instantaneous Frequency 0.407478 0.007676 0.300288 0.012361
Traceback (most recent call last):
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 75, in analyze
    Y, Ygrid, X[:, i], m, num_resamples, conf_level)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 124, in bias_reduced_delta
    d[i] = calc_delta(Y[r], Ygrid, X[r], m)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 106, in calc_delta
    fyc = gaussian_kde(Y[ix], bw_method='silverman')(Ygrid)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\stats\kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance) # IDM replaced inv by pinv
  File "C:\Temp\Python\Python36\lib\site-packages\scipy\linalg\basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2d_Delta_Indices.py", line 179, in <module>
    Si= delta.analyze(problem, attribute_data, classification_data[:,count], num_resamples= bootstrap, print_to_console= True)
  File "C:\Temp\Python\Python36\lib\site-packages\SALib\analyze\delta.py", line 88, in analyze
    raise np.linalg.LinAlgError(msg)
numpy.linalg.linalg.LinAlgError: Singular matrix detected
This may be due to the sample size (20099) being too small
If this is not the case, please raise an issue with the
SALib team

I attached the script and input data. Hoping that this new information

 can help you to diagnostic this issue.

Many thanks for all!

Ivan


[2d_Delta_Indices.zip](https://github.com/SALib/SALib/files/3204567/2d_Delta_Indices.zip)

**Comment by ConnectedSystems** [comment] 2019-05-22 02:29
Thanks for the files @ivan-marroquin I am travelling again today but will try to look at it soon

**Comment by ConnectedSystems** [comment] 2019-05-22 10:35
Hi again,

Seems I am missing some files...

`OSError: 2d_th_bed_n_noise.txt not found.`

**Comment by ivan-marroquin** [comment] 2019-05-22 19:49
Sorry for the confusion. Try this file.

[2d_Delta_Indices.zip](https://github.com/SALib/SALib/files/3209056/2d_Delta_Indices.zip)

**Comment by ConnectedSystems** [comment] 2019-05-26 12:35
Okay, so your code gets into a situation where identical values happen to get selected from `Y`, resulting in a singular value matrix - so it was in fact similar to what was happening in #240 and not a package version issue as I initially suspected.

I've made an adjustment to the code on my `delta-analyze-warn` branch to handle this particular case. Your script runs to completion with the latest changes in my branch.

Do the following (again) to get the updated code.

```bash
pip uninstall SALib
pip install git+https://github.com/ConnectedSystems/SALib@delta-analyze-warn
```

Let me know how you go

**Comment by ivan-marroquin** [comment] 2019-05-27 12:45
Hi @ConnectedSystems,

Thank you so much! I will be back to my office tomorrow, and let you know how the test goes.

Kind regards,
Ivan

**Comment by ivan-marroquin** [comment] 2019-05-30 16:20
Hi @ConnectedSystems ,

I ran several tests. In all of them, the fix worked pretty well! Thanks for your help.

May I ask you the following: how this issue was fixed in the code?

Kind regards,
Ivan

**Comment by ConnectedSystems** [comment] 2019-05-31 07:17
Hi @ivan-marroquin 

A similar issue was reported by @antonia-had and a proposed fix submitted (see issue #240) - in that case a matrix of all zeros was being created in the delta analysis process.

Your case was similar with the exception that a non-zero matrix of identical values was being created, which the proposed fix did not catch. I simply adjusted the fix to check that the matrix is filled with non-unique values rather than checking for non-zeros specifically.

The specific section changed is [here](https://github.com/ConnectedSystems/SALib/blob/3535dcd7eb55c562e586c1f20160fe6978ae9ac1/src/SALib/analyze/delta.py#L107)

I will be submitting a PR in the coming days and encourage both you and @antonia-had to have a look at the code for the proposed fix.

**Comment by ivan-marroquin** [comment] 2019-05-31 13:10
HI @ConnectedSystems ,

Thanks a lot for sharing the fix and for your help!

Ivan

**Comment by ConnectedSystems** [comment] 2019-06-06 13:31
Hi Ivan

I just submitted PR #251 - I couldn't seem to get GitHub to recognize your handle so I'm contacting you directly. If you're willing to spare the time I would encourage you to be involved in the review process of the PR

All the best!

**Comment by ivan-marroquin** [comment] 2019-06-07 17:40
Hi @ConnectedSystems 

Sorry for the late reply. Yes, I would like to help as much possible in the review process. Please, let me know how I can help.

Kind regards,
Ivan

**Comment by ConnectedSystems** [comment] 2019-06-09 12:25
Thanks @ivan-marroquin but looks like it's acceptable as is.

@jdherman please go ahead and close this issue as this is resolved by PR #251

**Closed** 2019-06-09 15:17 UTC

**Comment by ivan-marroquin** [comment] 2019-06-10 12:30
Hi @jdherman  and @ConnectedSystems 

Do you know when this fix will be made available to SALib distribution?

Many thanks,
Ivan

**Comment by jdherman** [comment] 2019-06-10 14:39
It's already on pypi in version 1.3.7
