### ISSUE TITLE
delta.analyze randomly returns singular matrix error

### ISSUE THREAD

**Issue by gbellandi** [SALib/SALib#151] opened 2017-06-29 08:13 UTC
Dear,
 feeding the `delta.analyze()` function with:
```
problem = {
  'num_vars': 3,
  'names': ['K_IO_AOBden', 'K_SO_AOBden', 'K_SNO_AOBden'],
  'bounds': [[0.01, 11], [0.01, 13.2], [0.08, 4.3]]
}
```
```
In: param_values
Out: array([[  2.12591411,   1.8200793 ,   0.10082878],
       [  6.21754537,   5.85214066,   2.8846046 ],
       [  8.01209459,  12.95017617,   1.00034018],
       [ 10.72587215,   9.03629573,   1.88932555],
       [  4.17005179,   1.30648717,   3.7287254 ],
       [  3.24299291,   3.44273292,   4.01808892],
       [  8.80676551,  10.03481953,   1.43068963],
       [  0.29322542,   6.80514303,   2.43057428]])
```
and
`metric` (a simple average value of the last 100 points of my time series output)

I randomly (meaning that sometimes it works out and gives the output normally and sometimes not) get the following error:

```
...................python2.7/site-packages/SALib/analyze/delta.pyc in calc_delta(Y, Ygrid, X, m)
     89         ix = np.where((xr > m[j]) & (xr <= m[j + 1]))[0]
     90         nm = len(ix)
---> 91         fyc = gaussian_kde(Y[ix], bw_method='silverman')(Ygrid)
     92         d_hat += (nm / (2 * N)) * np.trapz(np.abs(fy - fyc), Ygrid)
     93 

...................python2.7/site-packages/scipy/stats/kde.pyc in __init__(self, dataset, bw_method)
    170 
    171         self.d, self.n = self.dataset.shape
--> 172         self.set_bandwidth(bw_method=bw_method)
    173 
    174     def evaluate(self, points):

...................python2.7/site-packages/scipy/stats/kde.pyc in set_bandwidth(self, bw_method)
    497             raise ValueError(msg)
    498 
--> 499         self._compute_covariance()
    500 
    501     def _compute_covariance(self):

...................python2.7/site-packages/scipy/stats/kde.pyc in _compute_covariance(self)
    508             self._data_covariance = atleast_2d(np.cov(self.dataset, rowvar=1,
    509                                                bias=False))
--> 510             self._data_inv_cov = linalg.inv(self._data_covariance)
    511 
    512         self.covariance = self._data_covariance * self.factor**2

...................python2.7/site-packages/scipy/linalg/basic.pyc in inv(a, overwrite_a, check_finite)
    817         inv_a, info = getri(lu, piv, lwork=lwork, overwrite_lu=1)
    818     if info > 0:
--> 819         raise LinAlgError("singular matrix")
    820     if info < 0:
    821         raise ValueError('illegal value in %d-th argument of internal '

LinAlgError: singular matrix
```

Might be useful to know that increasing the `num_resamples` the error occurs more often (i.e. with 5 resamples occurs every 3 times, while using a resample of 15 you almost always get the error)

Do you think this is due to a bug in SALib or scipy, or rather something I'm missing?

**Comment by willu47** [comment] 2017-06-29 09:05
Hi @gbellandi, thanks for the comprehensive bug report.  This will make it easy to replicate the error and quicker to find a fix.  

Just to confirm, you are using Python 2.7, and which version of SALib?

**Comment by gbellandi** [comment] 2017-06-29 09:14
Hi, @willu47 happy to hear this can be useful.
I'm using SALib 1.0.3

**Comment by willu47** [comment] 2017-06-29 09:36
Exactly how are you calling `delta.analyze()`?

**Comment by willu47** [comment] 2017-06-29 09:57
So, I think the error is caused by having a small sample, which is an interesting corner case!  If you use a larger value for N (more model runs), then you should avoid getting this error.  In the meantime, I'll flag this for a fix.  @jdherman - do you want to take a look at this (I note that there are very few tests for the delta method too...)

**Comment by gbellandi** [comment] 2017-06-29 10:03
Interesting! It actually was a test with few models run indeed.
I think I'm calling the `delta.analyze(problem, param_values, metric)` in the same way as you showed

**Comment by willu47** [comment] 2017-06-29 11:12
Great, okay, I've opened #152 to address the bug and will close this issue.

**Closed by willu47** 2017-06-29 11:12 UTC
Labels: bug
