### ISSUE TITLE
Negative sobol indices

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#306] opened 2020-04-24 23:09 UTC
Hei again.
I am using SALib (SOBOL and Morris method)in my master assignment and the model I study is system of 3 nonlinear ODE which represent a interaction between bacteria and two microorganisms that feed on them.I am doing the sensitivity analysis for the interior equilibrium point and (Max,mean,median,equilibrium value ) of each of the dimensional and non-dimensional model  output which they are three.

Today I was wondering how to interpret the negative values of S1 and S2 indices because they should be positive as I have read. Should I trust my results.?

I have read three issues about similar problems.You have mentioned that two solutions:
 1)increase the sample size which I did ( I  tested for N=2400 and N=5000) but still get negative values for S1 and S2. By they way is there a thumb rule for appropriate sample size?I want to mention that with N=5000 It take some hours to get output.
2)If the negative values are small and the confidence interval include zero then I can treat them as zero. But the confidence interval is just one number in Sobol method so I don't know how it will include zero?
The other issue is that the Morris and Sobol doesn't give similar results.I have read same papers which says that mu_star in Morris is equivalent to S_T Sobol but this is not entirely correct in my case so I wonder hoe to interpret Morris method indices.
The attached code is for sensitivity analysis of the dimensional model outputs  and it is a jupyter Notebook.
[GSA_InitialValue-DimModel-Solv_ivp.zip](https://github.com/SALib/SALib/files/4531932/GSA_InitialValue-DimModel-Solv_ivp.zip)

**Comment by ConnectedSystems** [comment] 2020-04-25 00:54
Hello

I'll respond to your questions related to sensitivity analysis in this post. I did look through your code and noted some places where performance could be improved, but will expand on that in a separate response.

As you said, negative indices can be due to insufficient samples. It may be that 5000 is not enough.

The CI value can be interpreted as being +/- the reported `S` value.

Could you point me to the paper that states mu_star is equivalent to S_T? I don't think that is correct but there is likely some context missing.

Regarding determining appropriate sample sizes, I have seen suggestions in the past of ~1000 per parameter for Sobol, so in your case it would be ~15,000. Unfortunately what an appropriate sample size is depends on your model and modeling context so even that piece of guidance may be inappropriate.

Fig 3 in the paper below gives some indications of the order of magnitude number of samples you need for a particular purpose.

> Pianosi, F., Beven, K., Freer, J., Hall, J.W., Rougier, J., Stephenson, D.B., Wagener, T., 2016. Sensitivity analysis of environmental models: A systematic review with practical workflow. Environmental Modelling & Software 79, 214–232. https://doi.org/10.1016/j.envsoft.2016.02.008

One approach is to progressively increase your sample size until you reach convergence in the reported S values. Put simply, increase samples until the reported values become stable.

> Herman, J.D., Kollat, J.B., Reed, P.M., Wagener, T., 2013. Technical Note: Method of Morris effectively reduces the computational demands of global sensitivity analysis for distributed watershed models. Hydrology and Earth System Sciences 17, 2893–2903. https://doi.org/10.5194/hess-17-2893-2013

If you're only interested in determining what parameters are insensitive you could insert a dummy parameter in your model - one that is completely inactive and does nothing. Progressively increase sample size and assume all parameters with similar S values to that of the dummy parameter are insensitive.

> Khorashadi Zadeh, F., Nossent, J., Sarrazin, F., Pianosi, F., van Griensven, A., Wagener, T., Bauwens, W., 2017. Comparison of variance-based and moment-independent global sensitivity analysis approaches by application to the SWAT model. Environmental Modelling & Software 91, 210–222. https://doi.org/10.1016/j.envsoft.2017.02.001

**Comment by FO2020** [comment] 2020-04-25 07:49
Thanks for the reply and going through my code.
1- If I set the number of samples to N=15000 then number of model evaluation will be N*(2*num_par+2)=480000 which is much for a computer to handle.I am running this now and not sure that it will give results in the end. 
![SobolS1x](https://user-images.githubusercontent.com/61733579/80273869-6000a600-86d6-11ea-98b6-bc3878c10101.png)
2- What do you mean by reported S value ,is it the value we get in the table if so the CI for x0 in the previos table will be [ 3.301095e-02 -  9.997247e-01 , 3.301095e-02 -  9.997247e-01]=[-0.967,1.033] which will then include zero?
3-In this article ( same reference on SALib site ) 
https://www.asc.ohio-state.edu/statistics/comp_exp/jour.club/CamCarSal_EngModellingSoftware-2007.pdf
Thy mentioned something like that in the conclusion.

**Comment by ConnectedSystems** [comment] 2020-04-25 09:05
Hello,

1) Yes it is a lot.

In regards to your code I would suggest:

Remove all print statements - printing is an expensive operation.

```python
%%timeit
runs = 5000 * (2*15 + 2)
for i in range(runs):
    print("something")
# 17.8 s ± 1.33 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```python
%%timeit
runs = 5000 * (2*15 + 2)
for i in range(runs):
    i
# 3.54 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Likewise, save the latex representations of the results to a file rather than printing them.
On that note, don't display plots unless you really need them.

**Pre-allocate arrays so Python doesn't have to constantly resize them**

Gets you a minor speed increase. The increase will be bigger the larger the array.
Note that for sufficiently small arrays, Python lists will be as or more efficient.

```python
%%timeit
a = []
b = []
runs = 15000 * (2*15 + 2)
for i in range(runs):
    a.append(i / 2.0)
    b.append(i * 2.0)

# 140 ms ± 4.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

```python
%%timeit
runs = 5000 * (2*15 + 2)
a = np.empty(runs)
b = np.empty(runs)
for i in range(runs):
    a[i] = i / 2.0
    b[i] = i * 2.0

# 113 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Another advantage of this is that you can get rid of that long block of code where you're just converting lists into numpy arrays.


**Move the definition of `dynamical_model_bacteria()` outside your loops**
Python is a dynamic language - having the function definition inside the loops means it gets re-created in every iteration.

I know why it's declared inside the loop (you want to use local variables) but see the code block below to make this generic.

**Consolidate your model run loops into one function**
In actuality this will increase runtime a tiny bit, but will make your code cleaner as there are a lot of duplicate code and values being used.

```python
### NOTE:
# For this to work, ensure you have cython and scipy v1.4.1 installed. 
# Earlier versions of scipy have a bug in `solve_ivp` that prevents the 
# passing of additional arguments to the target function

# Installation:
# conda install scipy==1.4.1
#
# If using conda-forge:
# conda install -c conda-forge scipy==1.4.1

def dynamical_model_bacteria(t, X, r, k, f1, f2, epsilon1, 
                            omega11, psi12, beta1, epsilon2, phi12, 
                            omega22, beta2):
    x, y1, y2 = X
    dxdt=x*(r*(1.0-x/k)-f1*y1-f2*y2)
    dy1dt=y1* (-epsilon1-omega11*y1-psi12*y2+beta1*f1*x)          
    dy2dt=y2*(-epsilon2+phi12*y1-omega22*y2+beta2*f2*x)
    
    return dxdt,dy1dt,dy2dt


# In[73]:


import numpy as np
from numpy import median, amax, mean
import time

def run_model(param_values):
    loop_n = param_values.shape[0]

    # Reduce number of arrays to reduce number of array access
    # also makes your code more readable
    x_res = np.empty((loop_n, 4))
    y1_res = np.empty((loop_n, 4))
    y2_res = np.empty((loop_n, 4))
    
    t = [0, 60]
    t_eval_pts = np.linspace(0, 60, 8000)
    for i in range(loop_n):
        k,r,f1,f2,beta1, beta2, epsilon1,epsilon2,phi12,psi12,omega11,omega22,x0,y10,y20 = param_values[i]

        X0 = [x0, y10, y20]
        arg_list = (r, k, f1, f2, epsilon1, omega11, psi12, beta1, epsilon2, phi12, omega22, beta2)
        sol = solve_ivp(dynamical_model_bacteria, t, X0, 
                        args=arg_list, 
                        t_eval=t_eval_pts)

        x, y1, y2 = sol.y
        x_res[i, :] = amax(x), mean(x), median(x), x[-1]
        y1_res[i, :] = amax(y1), mean(y1), median(y1), y1[-1]
        y2_res[i, :] = amax(y2), mean(y2), median(y2), y2[-1]
    # End for

    return x_res, y1_res, y2_res
```

**If you can, try numba to compile `dynamical_model_bacteria()`**

This will reduce runtime a little bit, but unfortunately, the vast majority of the runtime is inside
`solve_ivp()`. 

2) What I meant was:
`[9.997247e-01 - 3.301095e-02 , 9.997247e-01 + 3.301095e-02]`

3) Thanks for the reference.

Note they do not claim they are equivalent, just that in their particular case the reported `mu_star` values could be used as a proxy of what S_T may be.

4) I've mis-remembered the details. Seems they just applied a large sample size in the first instance (N=9000). But you could try it with Morris.

**Comment by FO2020** [comment] 2020-04-25 14:56
I appreciate very much your suggestions to improve the code and other ideas.
1- Actually I thought about using empty function but there was something I couldn't understand about it which made me keep the lists. Of course what you did improve the performance. 
I still need to rename the output maybe like this (if you don't suggest better method) to loop through when running the sobol analysis
`x_Max,x_Mean,x_Median,x_End= np.transpose(x_res)
y1_Max,y1_Mean,y1_Median,y1_End= np.transpose(y1_res)
y2_Max,y2_Mean,y1_Median,y2_End= np.transpose(y1_res)
SOBOL=[ x_Max, y1_Max,y2_Max, x_Mean,y1_Mean,y2_Mean,x_Median,y1_Median,y1_Median,x_End,y1_End, y2_End]`
3-I wasn't very familiar with solv_ivp and used odeint but I had to use solve_ivp because it include implicit methods which I needed for the non-dimensional version of the model .How we can vectorize the code more? I would like to see how. Actually I have been used python just this year and was using matlab before.
4-If that is the CI then it mostly include zero ( tested it for some parameters) then I can treat them as zero as mentioned in issue #102.
https://github.com/SALib/SALib/issues/102
4-What I want actually is to know both sensitive and non sensitive parameters to maybe fix the non-influential ones and estimate the remaining but in my case it seems that that Total effect is the most important one as others are very small.

**Comment by ConnectedSystems** [comment] 2020-04-25 15:28
1) I would rewrite subsequent functions to just expect arrays related to `x`, `y1`, and `y2`
I think it would end up being less code and more understandable.

That said, if you don't want to mess with what you have right now:

```python
SOBOL = [i for i in x_res.T] + [i for i in y1_res.T] + [i for i in y2_res.T]
```
3) To vectorize, `solve_ivp` would have to accept arrays of inputs which it doesn't look like it can.
It may be worthwhile parallelizing (I recommend the `multiprocess` package over the built-in `multiprocessing`) but this may take more time than you're willing to spend. See https://github.com/uqfoundation/multiprocess/ if interested.

In my own tests, making your functions parallel did not help much as Python would spend too much time sending data around. For very large number of runs though (like in your case) it may help.

4. Provided the confidence intervals are not overly large (like in some of the figures you originally plot) then yes, it indicates insensitivity


> in my case it seems that that Total effect is the most important one as others are very small.

Is this the Total Sensitivity Index (S_T)? This indicates the influence of a parameter and its interaction with other parameters.

5. No idea what's happening there, sorry. Without knowing what the error is its hard to tell. My first hunch is when you're copy/pasting it's mixing tabs and spaces but that's just a guess.

6. 

```python
# Assuming you're using Python 3.6
with open("latex_output.txt", "w+") as latex_file:
    print(df.to_latex(), file=latex_file)
    print(df2.to_latex(), file=latex_file)
    # ... and so on...
```

`w+` creates the file if it does not exist. Overwrites if it does exist.

See list of file modes here:
https://stackabuse.com/file-handling-in-python/

**Comment by FO2020** [comment] 2020-04-25 16:37
Thank again for your reply.
1-I don't get any errors messages when running the cell contains the ODE solver. But geting error at the next cell 
```
NameError                                 Traceback (most recent call last)
<ipython-input-30-3f0f4b7d9e69> in <module>
----> 1 x_Max,x_Mean,x_Median,x_End= np.transpose(x_res)
      2 y1_Max,y1_Mean,y1_Median,y1_End= np.transpose(y1_res)
      3 y2_Max,y2_Mean,y1_Median,y2_End= np.transpose(y2_res)
      4 SOBOL=[ x_Max, y1_Max,y2_Max, x_Mean,y1_Mean,y2_Mean,x_Median,y1_Median,y1_Median,x_End,y1_End, y2_End]

NameError: name 'x_res' is not defined
```
[Untitled7.zip](https://github.com/SALib/SALib/files/4533518/Untitled7.zip)
2- When tring to save latex inside for loop I get just S2 for x written in the file while I want all the MAX_Sobol in the file.
```
MAX_Sobol=[STx_Max,S1x_Max,S2x_Max,STy1_Max,S1y1_Max,S2y1_Max,STy2_Max,S1y2_Max,S2y2_Max]
MEAN_Sobol=[STx_Mean,S1x_Mean,S2x_Mean,STy1_Mean,S1y1_Mean,S2y1_Mean,STy2_Mean,S1y2_Mean,S2y2_Mean]
MEDIAN_Sobol=[STx_Median,S1x_Median,S2x_Median,STy1_Median,S1y1_Median,S2y1_Median,STy2_Median,S1y2_Median,S2y2_Median]
END_Sobol=[STx_End,S1x_End,S2x_End,STy1_End,S1y1_End,S2y1_End,STy2_End,S1y2_End,S2y2_End]
```

**Comment by ConnectedSystems** [comment] 2020-04-26 04:00
Glad you found the reason. Feel free to close if this issue is resolved.

Just FYI, it's best practice to have file handlers outside loops:

```python
# This will open/close the file every iteration (slow performance)
# with the file opened in "w+" mode, it will keep overwriting
# so you only see the last output
for df in list_of_dfs:
    with open("latex_output.txt", "w+") as latex_file:
        print(df.to_latex(), file=latex_file)

# This will only open the file once
# Because it is only opened once, all output is retained in the file
with open("latex_output.txt", "w+") as latex_file:
    for df in list_of_dfs:
        print(df.to_latex(), file=latex_file)
```

**Comment by FO2020** [comment] 2020-04-26 11:29
Hei ,and thanks for replying.
 I used the second one because it tried both before seeing your reply.
I tried today to calculate S1 for the interior equilibrium point of the non-dimensional system via Sobol, rbd_fast and Delta moment independent measure but got different results. Shouldn't they be the same?
S1 sobol for x coordinate
![Sensitivity of $x$ coordinate  of the interior equilibrium pointNonDimModelFirstSobol](https://user-images.githubusercontent.com/61733579/80306048-0d4fe880-87c1-11ea-88be-ddbaf0c31aed.png)

S1 via delta method
![Sensitivity of $x$ coordinate  of the interior equilibrium pointNonDimModelFirstDMIM](https://user-images.githubusercontent.com/61733579/80306061-28baf380-87c1-11ea-9d22-56bd0b50d052.png)

S1 via rbd_fast
![Sensitivity of $x$ coordinate  of the interior equilibrium pointNonDimModelFirstRbdFast](https://user-images.githubusercontent.com/61733579/80306163-daf2bb00-87c1-11ea-9824-83d5fc00c5d1.png)
The used code is:
[GSA_InteriorEP_NonDimVar_NonDim_model_New.zip](https://github.com/SALib/SALib/files/4535195/GSA_InteriorEP_NonDimVar_NonDim_model_New.zip)

**Comment by ConnectedSystems** [comment] 2020-04-26 15:44
> Shouldn't they be the same?

Ideally (or perhaps, hypothetically) all methods are capable of coming to the same or similar conclusions. In practice however, it may not be the case. Each approach has its own pros and cons, and the results themselves may be sensitive to the context of the model and sample size which varies depending, again, on the properties of the model. It may be that one approach is less suitable than another for your model or the context in which you're applying your model. Difference in sampling will affect results as well as one may be exploring different regions of parameter space to another.

You could plot these results with the order of parameters the same and CI values removed so that you can compare the values for each parameter. 

I haven't looked at your code this time, but the plot of Sobol results with the relatively large and fairly constant CIs look strange to me. Are you making it yourself or is this with the built-in convenience plotting method?

**Comment by FO2020** [comment] 2020-04-26 15:48
No I am using the barplot which is mentioned in the SALib site.I used fairly large sampes . Delta and rbd_fast have more smiliar S1 than Sobol

**Comment by ConnectedSystems** [comment] 2020-04-26 16:16
If that's the case, I would try a higher bootstrap resample value for Sobol to see if that gives you a better indication of CIs.

Closer to the issue at hand however, do you need all the results to be the same and if so, have you checked for convergence?

Another thing is that the Sobol and RBD-FAST results you've shown indicate those parameters are insensitive. If delta and RBD-FAST have similar S1, then delta is also saying these parameters are insensitive. Essentially you have consensus across all the methods you have tried, even though the ranking may differ.

Do you see this similarity for the other 7 parameters? (you have 15 if I recall correctly)

**Comment by FO2020** [comment] 2020-04-26 16:55
Hei,
I have the dimensionsl  model with 15 input factors (12 parameters + 3 initial values) and the interior equilibrum point for the system for which I have a Mathematical expression (number of parameter for this will be 12).
Nondimensional model : number of input factors =11 (8 parameters + 3 initial values)
Interior EP for this : number of input factor =num of parameters =8
The figures in the previos post was for interior equilibrum point for the NON dimensional model which I called EP_5 in the code.
I changed the resamples from 100 to 500 and so 1000 and nothing changed. 
Omega11 in Sobol is at the END while in third place in delta and rbd_fast  which is strange. All results  are ordered in decending order.
I haven’t checked this for the whole model but I have to check if the results are equivalent across methods

**Comment by ConnectedSystems** [comment] 2020-04-27 00:21
Hello again,

Given we're starting to wander away from the originally raised issue, and this new topic of concern is not specific to SALib I'm going to close this. I'd suggest asking for input on interpreting your results on stackoverflow if you need.

Some directions for further thought however:

- As the results are close to zero, the rankings does not indicate much. They are all insensitive.
- It could also be a bug in the model and the results are in fact not being outputted/logged correctly, and could explain why all parameters seem to be insensitive. I have had the unfortunate experience of this happening to me from a third-party model.
- In relation to the above, see if the Sobol Total Order values are similarly small.
- A quick way to test if your model is working correctly is to pick a parameter you would expect to have a large effect and run the model directly using the lower and upper values. Repeat for each parameter if needed. If the results do not change much, then the issue is with the model or logging of results.


All the best with your Masters

**Closed by ConnectedSystems** 2020-04-27 00:21 UTC
Labels: question_interpretation

**Comment by FO2020** [comment] 2020-04-27 00:31
Hei, Thanks again for the using time to answer my issue. You have been to great help with respect to sensitivity and code performance.
